name: HiByeCraftCore
main: com.anson.mc.main.HiByeCraftCore
version: 1.0.0
author: AnsonTsang
commands:
  hbccreload:
    description: Used for reload
    usage: /hbccreload <lang / config>
  skill:
    description: HiByeCraft Skill
    usage: /skill <skill type>