name: HiByeCraftCore
main: com.anson.mc.hbc.core.main.HiByeCraftCore
version: 1.0.0
author: AnsonTsang
commands:
  hbc:
    description: General For HiByeCraft
  skill:
    description: HiByeCraft Skill
  help: